package br.com.abril.nds.model.fiscal;

public enum OrigemItem {

	ESTOQUE,
	FECHAMENTO_CE_INTEGRACAO,
	MOVIMENTO_ESTOQUE_COTA, 
	DEVOLUCAO_FORNECEDOR, 
	MOVIMENTO_ESTOQUE, 
	MOVIMENTO_FECHAMENTO_FISCAL_COTA, 
	MOVIMENTO_FECHAMENTO_FISCAL_FORNECEDOR,
	
}