package br.com.abril.nds.model.financeiro;

public enum StatusBaixa {
	
	PAGO,
	PAGAMENTO_PARCIAL,
	PAGO_DIVERGENCIA_VALOR,
	PAGO_DIVERGENCIA_DATA,
	PAGO_BOLETO_NAO_ENCONTRADO,
	
	NAO_PAGO_DIVERGENCIA_VALOR,
	NAO_PAGO_DIVERGENCIA_DATA,
	NAO_PAGO_BAIXA_JA_REALIZADA;

}
