--Apaga a tabela criada na exportação do entidade (ViewContaCorrente)

DROP TABLE IF EXISTS VIEW_CONTA_CORRENTE_COTA;

--Cria a view correspondente a entidade (ViewContaCorrente)

CREATE OR REPLACE VIEW VIEW_CONTA_CORRENTE_COTA AS (SELECT CONSOLIDADO_FINANCEIRO_COTA.ID AS ID, CONSOLIDADO_FINANCEIRO_COTA.COTA_ID AS COTA_ID, COTA.NUMERO_COTA AS NUMERO_COTA, CONSOLIDADO_FINANCEIRO_COTA.CONSIGNADO AS CONSIGNADO, CONSOLIDADO_FINANCEIRO_COTA.DT_CONSOLIDADO AS DT_CONSOLIDADO, CONSOLIDADO_FINANCEIRO_COTA.DEBITO_CREDITO AS DEBITO_CREDITO, CONSOLIDADO_FINANCEIRO_COTA.ENCALHE AS ENCALHE, CONSOLIDADO_FINANCEIRO_COTA.ENCARGOS AS ENCARGOS, CONSOLIDADO_FINANCEIRO_COTA.NUMERO_ATRASADOS AS NUMERO_ATRASADOS, CONSOLIDADO_FINANCEIRO_COTA.PENDENTE AS PENDENTE, CONSOLIDADO_FINANCEIRO_COTA.TOTAL AS TOTAL, CONSOLIDADO_FINANCEIRO_COTA.VALOR_POSTERGADO AS VALOR_POSTERGADO, CONSOLIDADO_FINANCEIRO_COTA.VENDA_ENCALHE AS VENDA_ENCALHE, 'CONSOLIDADO' AS TIPO FROM CONSOLIDADO_FINANCEIRO_COTA INNER JOIN COTA ON COTA.ID=CONSOLIDADO_FINANCEIRO_COTA.COTA_ID) UNION (SELECT 0 AS ID, COTA.ID AS COTA_ID, COTA.NUMERO_COTA AS NUMERO_COTA, NULL AS CONSIGNADO, COBRANCA.DT_EMISSAO AS DT_CONSOLIDADO, NULL AS DEBITO_CREDITO, NULL AS ENCALHE, NULL AS ENCARGOS, NULL AS NUMERO_ATRASADOS, COBRANCA.VALOR AS PENDENTE, NULL AS TOTAL, NULL VALOR_POSTERGADO, NULL AS VENDA_ENCALHE, 'COBRANCA' AS TIPO FROM COBRANCA INNER JOIN COTA ON COTA.ID=COBRANCA.COTA_ID WHERE COBRANCA.STATUS_COBRANCA  = 'NAO_PAGO'     AND COBRANCA.DT_VENCIMENTO > (SELECT MAX(CONSOLIDADO_FINANCEIRO_COTA.DT_CONSOLIDADO) FROM CONSOLIDADO_FINANCEIRO_COTA));																																																																																																																		                                                																																																																																																																																																																																																																																															

--Apaga a tabela criada na exportação do entidade (ViewDesconto)

DROP TABLE IF EXISTS VIEW_DESCONTO;

--Cria a view correspondente a entidade (ViewDesconto)

DROP TABLE IF EXISTS VIEW_DESCONTO;

CREATE OR REPLACE VIEW VIEW_DESCONTO AS SELECT CASE tipo_produto.GRUPO_PRODUTO WHEN 'OUTROS' THEN produto.DESCONTO_LOGISTICA_ID ELSE desconto_produto_edicao.DESCONTO END AS DESCONTO, cota.ID AS COTA_ID, produto_edicao.ID AS PRODUTO_EDICAO_ID, fornecedor.ID AS FORNECEDOR_ID FROM desconto_produto_edicao, cota, produto, produto_edicao, tipo_produto, fornecedor WHERE desconto_produto_edicao.COTA_ID = cota.ID AND desconto_produto_edicao.PRODUTO_EDICAO_ID = produto_edicao.ID AND desconto_produto_edicao.FORNECEDOR_ID = fornecedor.ID AND produto_edicao.PRODUTO_ID = produto.ID AND produto.TIPO_PRODUTO_ID = tipo_produto.ID;
	
--Cria as tabelas do Quartz

CREATE TABLE IF NOT EXISTS QRTZ_JOB_DETAILS(SCHED_NAME VARCHAR(120) NOT NULL,JOB_NAME  VARCHAR(200) NOT NULL,JOB_GROUP VARCHAR(200) NOT NULL,DESCRIPTION VARCHAR(250) NULL,JOB_CLASS_NAME   VARCHAR(250) NOT NULL,IS_DURABLE VARCHAR(1) NOT NULL,IS_NONCONCURRENT VARCHAR(1) NOT NULL,IS_UPDATE_DATA VARCHAR(1) NOT NULL,REQUESTS_RECOVERY VARCHAR(1) NOT NULL,JOB_DATA BLOB NULL,PRIMARY KEY (SCHED_NAME,JOB_NAME,JOB_GROUP));

CREATE TABLE IF NOT EXISTS QRTZ_TRIGGERS(SCHED_NAME VARCHAR(120) NOT NULL,TRIGGER_NAME VARCHAR(200) NOT NULL,TRIGGER_GROUP VARCHAR(200) NOT NULL,JOB_NAME  VARCHAR(200) NOT NULL,JOB_GROUP VARCHAR(200) NOT NULL,DESCRIPTION VARCHAR(250) NULL,NEXT_FIRE_TIME BIGINT(13) NULL,PREV_FIRE_TIME BIGINT(13) NULL,PRIORITY INTEGER NULL,TRIGGER_STATE VARCHAR(16) NOT NULL,TRIGGER_TYPE VARCHAR(8) NOT NULL,START_TIME BIGINT(13) NOT NULL,END_TIME BIGINT(13) NULL,CALENDAR_NAME VARCHAR(200) NULL,MISFIRE_INSTR SMALLINT(2) NULL,JOB_DATA BLOB NULL,PRIMARY KEY (SCHED_NAME,TRIGGER_NAME,TRIGGER_GROUP),FOREIGN KEY (SCHED_NAME,JOB_NAME,JOB_GROUP) REFERENCES QRTZ_JOB_DETAILS(SCHED_NAME,JOB_NAME,JOB_GROUP));

CREATE TABLE IF NOT EXISTS QRTZ_SIMPLE_TRIGGERS(SCHED_NAME VARCHAR(120) NOT NULL,TRIGGER_NAME VARCHAR(200) NOT NULL,TRIGGER_GROUP VARCHAR(200) NOT NULL,REPEAT_COUNT BIGINT(7) NOT NULL,REPEAT_INTERVAL BIGINT(12) NOT NULL,TIMES_TRIGGERED BIGINT(10) NOT NULL,PRIMARY KEY (SCHED_NAME,TRIGGER_NAME,TRIGGER_GROUP),FOREIGN KEY (SCHED_NAME,TRIGGER_NAME,TRIGGER_GROUP)REFERENCES QRTZ_TRIGGERS(SCHED_NAME,TRIGGER_NAME,TRIGGER_GROUP));

CREATE TABLE IF NOT EXISTS QRTZ_CRON_TRIGGERS(SCHED_NAME VARCHAR(120) NOT NULL,TRIGGER_NAME VARCHAR(200) NOT NULL,TRIGGER_GROUP VARCHAR(200) NOT NULL,CRON_EXPRESSION VARCHAR(200) NOT NULL,TIME_ZONE_ID VARCHAR(80),PRIMARY KEY (SCHED_NAME,TRIGGER_NAME,TRIGGER_GROUP),FOREIGN KEY (SCHED_NAME,TRIGGER_NAME,TRIGGER_GROUP)REFERENCES QRTZ_TRIGGERS(SCHED_NAME,TRIGGER_NAME,TRIGGER_GROUP));

CREATE TABLE IF NOT EXISTS QRTZ_SIMPROP_TRIGGERS(SCHED_NAME VARCHAR(120) NOT NULL,TRIGGER_NAME VARCHAR(200) NOT NULL,TRIGGER_GROUP VARCHAR(200) NOT NULL,STR_PROP_1 VARCHAR(512) NULL,STR_PROP_2 VARCHAR(512) NULL,STR_PROP_3 VARCHAR(512) NULL,INT_PROP_1 INT NULL,INT_PROP_2 INT NULL,LONG_PROP_1 BIGINT NULL,LONG_PROP_2 BIGINT NULL,DEC_PROP_1 NUMERIC(13,4) NULL,DEC_PROP_2 NUMERIC(13,4) NULL,BOOL_PROP_1 VARCHAR(1) NULL,BOOL_PROP_2 VARCHAR(1) NULL,PRIMARY KEY (SCHED_NAME,TRIGGER_NAME,TRIGGER_GROUP),FOREIGN KEY (SCHED_NAME,TRIGGER_NAME,TRIGGER_GROUP) REFERENCES QRTZ_TRIGGERS(SCHED_NAME,TRIGGER_NAME,TRIGGER_GROUP));

CREATE TABLE IF NOT EXISTS QRTZ_BLOB_TRIGGERS(SCHED_NAME VARCHAR(120) NOT NULL,TRIGGER_NAME VARCHAR(200) NOT NULL,TRIGGER_GROUP VARCHAR(200) NOT NULL,BLOB_DATA BLOB NULL,PRIMARY KEY (SCHED_NAME,TRIGGER_NAME,TRIGGER_GROUP),FOREIGN KEY (SCHED_NAME,TRIGGER_NAME,TRIGGER_GROUP)REFERENCES QRTZ_TRIGGERS(SCHED_NAME,TRIGGER_NAME,TRIGGER_GROUP));

CREATE TABLE IF NOT EXISTS QRTZ_CALENDARS(SCHED_NAME VARCHAR(120) NOT NULL,CALENDAR_NAME  VARCHAR(200) NOT NULL,CALENDAR BLOB NOT NULL,PRIMARY KEY (SCHED_NAME,CALENDAR_NAME));

CREATE TABLE IF NOT EXISTS QRTZ_PAUSED_TRIGGER_GRPS(SCHED_NAME VARCHAR(120) NOT NULL,TRIGGER_GROUP  VARCHAR(200) NOT NULL, PRIMARY KEY (SCHED_NAME,TRIGGER_GROUP));

CREATE TABLE IF NOT EXISTS QRTZ_FIRED_TRIGGERS(SCHED_NAME VARCHAR(120) NOT NULL,ENTRY_ID VARCHAR(95) NOT NULL,TRIGGER_NAME VARCHAR(200) NOT NULL,TRIGGER_GROUP VARCHAR(200) NOT NULL,INSTANCE_NAME VARCHAR(200) NOT NULL,FIRED_TIME BIGINT(13) NOT NULL,PRIORITY INTEGER NOT NULL,STATE VARCHAR(16) NOT NULL,JOB_NAME VARCHAR(200) NULL,JOB_GROUP VARCHAR(200) NULL,IS_NONCONCURRENT VARCHAR(1) NULL,REQUESTS_RECOVERY VARCHAR(1) NULL,PRIMARY KEY (SCHED_NAME,ENTRY_ID));

CREATE TABLE IF NOT EXISTS QRTZ_SCHEDULER_STATE(SCHED_NAME VARCHAR(120) NOT NULL,INSTANCE_NAME VARCHAR(200) NOT NULL,LAST_CHECKIN_TIME BIGINT(13) NOT NULL,CHECKIN_INTERVAL BIGINT(13) NOT NULL,PRIMARY KEY (SCHED_NAME,INSTANCE_NAME));

CREATE TABLE IF NOT EXISTS QRTZ_LOCKS(SCHED_NAME VARCHAR(120) NOT NULL,LOCK_NAME  VARCHAR(40) NOT NULL, PRIMARY KEY (SCHED_NAME,LOCK_NAME));