package br.com.abril.nds.model.cadastro;

public enum TemaProduto {

    NEGOCIOS_ECONOMIA_POLITICA(1,"NEGOCIOS/ECONOMIA/POLITICA"),	
	IMPORTADAS(2,"IMPORTADAS"),		
	SEMANAIS_DE_INFORMACAO(3,"SEMANAIS DE INFOMACAO"),
	CARRO_MECAN_AUTOMOVEL(4,"CARRO/MECAN.AUTOMOVEL"),		
	INFANTIS_INTERESSE_GERAL(5,"INFANTIS INTERESSE GERAL"),		
	SAUDE(6,"SAUDE"),		
	CULINARIA(7,"CULINARIA"),		
	EDUCACAO_CURSO_OR_PROF(8,"EDUCACAO/CURSO/OR.PROF."),		
	OPORTUNIDADES(9,"OPORTUNIDADES"),		
	DECORACAO(10,"DECORACAO"),		
	QUADRINHOS_JOVENS(11,"QUADRINHOS JOVENS"),		
	CRUZADAS_PASSATEMPOS(12,"CRUZADAS/PASSATEMPOS"),		
	MANGA(13,"MANGA"),		
	COMPORTAMENTO_OUTROS(14,"COMPORTAMENTO OUTROS"),		
	PORNOGRAFIA(15,"PORNOGRAFIA"),		
	FUTEBOL_CLUBES(16,"FUTEBOL/CLUBES"),		
	CR_ANIMACAO_JAPONESA(17,"CR.ANIMACAO JAPONESA"),		
	CR_FUTEBOL(18,"CR.FUTEBOL"),		
	BEM_ESTAR(19,"BEM ESTAR"),		
	CIENCIA_E_INTER_GERAL(20,"CIENCIA E INTER. GERAL"),		
	COL_CURSOS_FORMACAO_TECNICA(21,"COL.CURSOS/FORMACAO TECNICA"),		
	CINE_VIDEO_ENTRETENIMENTO(22,"CINE/VIDEO (ENTRETENIMENTO)"),		
	TELEVISAO(23,"TELEVISAO"),		
	COL_DOCUMENTARIOS(24,"COL.DOCUMENTARIOS"),		
	HISTOR_MITOLOG_GEOGRAF_FILOSOF(25,"HISTOR/MITOLOG/GEOGRAF/FILOSOF"),		
	ASTROLOGIA_PREVISAO(26,"ASTROLOGIA/PREVISAO"),		
	COL_FEMININAS(27,"COL.FEMININAS"),		
	ATIVIDADES_INFANTIS(28,"ATIVIDADES INFANTIS"),		
	COL_INFANTIS(29,"COL.INFANTIS"),		
	COL_LITERATURA_EDUCACAO(30,"COL.LITERATURA EDUCACAO"),		
    COL_MASCULINAS(31,"COL.MASCULINAS"),		
	MODA(32,"MODA"),		
	MUSICA_ENTRETENIMENTO(33,"MUSICA (ENTRETENIMENTO)"),		
	CR_OUTROS(34,"CR.OUTROS"),		
	PUERICULTURA(35,"PUERICULTURA"),		
	CULTURA_LITERATURA_BIOGRAFIAS(36,"CULTURA/LITERATURA/BIOGRAFIAS"),		
	LIV_FICCAO(37,"LIV.FICCAO"),		
	ESTETICA(38,"ESTETICA"),		
	ARTESANATO_COM_LINHA(39,"ARTESANATO COM LINHA"),		
	FEMININAS_TWEENS(40,"FEMININAS TWEENS"),		
	HUMOR_COMEDIA(41,"HUMOR/COMEDIA"),		
	ANIMAIS_ESTIMACAO(42,"ANIMAIS ESTIMACAO"),		
	MOTO(43,"MOTO"),		
	NOIVAS_E_DEBUTANTES(44,"NOIVAS E DEBUTANTES"),		
	GUIA_DE_RUAS(45,"GUIA DE RUAS"),		
	GUIA_DE_TURISMO(47,"GUIA DE TURISMO"),		
	AGROBUSINESS(48,"AGROBUSINESS"),		
	LIV_NAO_FICCAO(49,"LIV.NAO FICCAO"),		
	ROMANCE(50,"ROMANCE"),		
	CR_ANIMAIS(52,"CR.ANIMAIS"),		
	INFORMACOES_ATUALIDADES(53,"INFORMACOES/ATUALIDADES"),		
	QUADRINHOS_ADULTO(54,"QUADRINHOS ADULTO"),		
	QUADRINHOS_INFANTIS(55,"QUADRINHOS INFANTIS"),		
	NAUTICA(56,"NAUTICA"),		
	ESPORTES_OUTROS(57,"ESPORTES OUTROS"),		
	ARQUITETURA_CONSTRUCAO(58,"ARQUITETURA/CONSTRUCAO"),		
	CORPO_E_DIETA(59,"CORPO E DIETA"),		
	CR_AUTOMOVEIS(60,"CR.AUTOMOVEIS"),		
	FOTOGRAFIA(61,"FOTOGRAFIA"),		
	INFORMATICA_TECNOLOGIA(62,"INFORMATICA/TECNOLOGIA"),		
	CR_BONECA(63,"CR.BONECA"),		
	JOGOS(64,"JOGOS"),		
	ESOTERISMO_ESPIRITUALIDADE(65,"ESOTERISMO/ESPIRITUALIDADE"),		
	MUSICA_CIFRADA(66,"MUSICA CIFRADA"),		
	AUTO_AJUDA(67,"AUTO AJUDA"),		
	GUIA_RODOVIARIO_MAPAS(68,"GUIA RODOVIARIO/MAPAS"),		
	TURISMO_ECOTURISMO(69,"TURISMO/ECOTURISMO"),		
	CR_FILME_ANIMACAO(70,"CR.FILME ANIMACAO"),		
	IDOLOS_E_ASTROS(71,"IDOLOS E ASTROS"),		
	ARTESANATO_LEVE(72,"ARTESANATO LEVE"),		
	CR_FILME_LIVE_ACTION(73,"CR.FILME LIVE ACTION"),		
	CR_HEROIS_ANIMACAO(74,"CR.HEROIS ANIMACAO"),		
	LIV_INFANTIS(75,"LIV.INFANTIS"),		
	CR_PERSONAGENS_INFANTIS(76,"CR.PERSONAGENS INFANTIS"),		
	CR_PREMIUM_PACKETS(77,"CR.PREMIUM PACKETS"),		
	CR_SERIADO_NOVELA_IDOLOS(78,"CR.SERIADO/NOVELA/IDOLOS"),		
	LIV_AUTO_AJUDA_ESOTERISMO(79,"LIV.AUTO-AJUDA/ESOTERISMO"),		
	ADMIN_PESSOAL_CARREIRA(82,"ADMIN.PESSOAL(CARREIRA)"),		
	FEMININAS_TEENS(86,"FEMININAS TEENS"),		
	FEMININAS_ADULTAS(87,"FEMININAS ADULTAS"),		
	FEMININAS_POPULARES(88,"FEMININAS POPULARES"),		
	COMPORTAMENTO_MASCULINO(89,"COMPORTAMENTO MASCULINO"),		
	CELEBRIDADES(90,"CELEBRIDADES"),		
	TUNING(97,"TUNING"),		
	OUTROS(99,"OUTROS");	
	
	private Integer codigo;
	
	private String descricao;
	
	private TemaProduto(Integer codigo,String descricao) {
		
		this.codigo = codigo;
		this.descricao = descricao;
	}
	
	public Integer getCodigo() {
		return codigo;
	}
	
	public String getDescTemaProduto(){
		return this.descricao;
	}

	@Override
	public String toString() {
		return this.descricao;
	}
	
}
