package br.com.abril.nds.model;

/**
 * @author francisco.garcia
 * @version 1.0
 * @created 14-fev-2012 11:35:32
 */
public enum Origem {
	MANUAL,
	INTERFACE,
	CARGA_INICIAL,
	TRANSFERENCIA_LANCAMENTO_FALTA_E_SOBRA,
	TRANSFERENCIA_LANCAMENTO_FALTA_E_SOBRA_FECHAMENTO_ENCALHE,
	TRANSFERENCIA_LANCAMENTO_FALTA_E_SOBRA_COTA,
	TRANSFERENCIA_PERDA_EM_DEVOLUCAO_ENCALHE_FORNECEDOR,
	TRANSFERENCIA_DEVOLUCAO_FORNECEDOR,
	TRANSFERENCIA_ESTORNO_DEVOLUCAO_FORNECEDOR,
	TRANSFERENCIA_ESTORNO_SOBRA_DEVOLUCAO_FORNECEDOR,
	TRANSFERENCIA_ESTORNO_PERDA_EM_DEVOLUCAO_ENCALHE_FORNECEDOR,
	//Trac 784
	PRODUTO_SEM_CADASTRO,
	INVENTARIO
}