DROP TABLE IF EXISTS CARGA_PRODIN_PRD;

create table CARGA_PRODIN_PRD (
codDistrib VARCHAR(7),
dataGeracaoArquivo VARCHAR(8),
contextoProd VARCHAR(1),
codForncProd VARCHAR(7),
codigoProduto VARCHAR(8),
codigoEdicao VARCHAR(4),
nome VARCHAR(30),
codigoBarras VARCHAR(18),
codigoBarrasCorporativo VARCHAR(18),
peso VARCHAR(5),
tipoProd VARCHAR(3),
peb VARCHAR(3),
largura VARCHAR(5),
comprimento VARCHAR(5),
espessura VARCHAR(5),
situacaoTributaria VARCHAR(1),
tributacaoFiscal VARCHAR(1),
pacotePadrao VARCHAR(8),
tipoMaterialPromocional VARCHAR(3),
tipoMaterialDivulgacao VARCHAR(3),
tipoMaterialTroca VARCHAR(3),
valorValeDesconto VARCHAR(10),
valorMaterialTroca VARCHAR(10),
formaComercializacao VARCHAR(3),
contemBrinde VARCHAR(1),
codNBM VARCHAR(10),
descBrinde VARCHAR(300),
condVendeSeparado VARCHAR(1),
status VARCHAR(1),
dataDesativacao VARCHAR(8),
chamadaCapa VARCHAR(30),
edicao VARCHAR(4),
tipoRecolhimento VARCHAR(1),
classeSocial VARCHAR(2),
periodicidade VARCHAR(3),
formaFiscal VARCHAR(2),
sexo VARCHAR(1),
idade VARCHAR(1),
lancamento VARCHAR(1),
temaPrincipal VARCHAR(2),
temaSecundario VARCHAR(2),
categoria VARCHAR(3),
contextoProdReferencia VARCHAR(1),
codFornecProdReferencia VARCHAR(1),
codProdReferencia VARCHAR(12),
tipoDesconto VARCHAR(2),
contextoEditor VARCHAR(1),
codigoEditor VARCHAR(7),
codContexto VARCHAR(1),
codFornecPublicacao VARCHAR(7),
codColecao VARCHAR(3),
formaInclusao VARCHAR(1),
codPublicacao VARCHAR(8),
campoObscuro VARCHAR(6),
nomeComercial VARCHAR(45),
classificacao VARCHAR(30),
segmento VARCHAR(2),
fornecedorId VARCHAR(1),
KEY codigoProdutoEdicao (codigoProduto,codigoEdicao)) 
-- ENGINE=MEMORY
;

LOAD DATA INFILE '/opt/rollout/load_files/00000001.prd' INTO TABLE CARGA_PRODIN_PRD CHARACTER SET UTF8
(@linha) SET 
codDistrib=SUBSTR(@linha,1,7),
dataGeracaoArquivo=SUBSTR(@linha,8,8),
contextoProd=SUBSTR(@linha,26,1),
codForncProd=SUBSTR(@linha,27,7),
codigoProduto=SUBSTR(@linha,34,8),
codigoEdicao=SUBSTR(@linha,42,4),
nome=SUBSTR(@linha,46,30),
codigoBarras=SUBSTR(@linha,76,18),
codigoBarrasCorporativo=SUBSTR(@linha,94,18),
peso=SUBSTR(@linha,112,5),
tipoProd=SUBSTR(@linha,117,3),
peb=SUBSTR(@linha,120,3),
largura=SUBSTR(@linha,123,5),
comprimento=SUBSTR(@linha,128,5),
espessura=SUBSTR(@linha,133,5),
situacaoTributaria=SUBSTR(@linha,138,1),
tributacaoFiscal=SUBSTR(@linha,139,1),
pacotePadrao=SUBSTR(@linha,140,8),
tipoMaterialPromocional=SUBSTR(@linha,148,3),
tipoMaterialDivulgacao=SUBSTR(@linha,151,3),
tipoMaterialTroca=SUBSTR(@linha,154,3),
valorValeDesconto=SUBSTR(@linha,157,10),
valorMaterialTroca=SUBSTR(@linha,167,10),
formaComercializacao=SUBSTR(@linha,177,3),
contemBrinde=SUBSTR(@linha,204,1),
codNBM=SUBSTR(@linha,205,10),
descBrinde=SUBSTR(@linha,217,300),
condVendeSeparado=SUBSTR(@linha,517,1),
status=SUBSTR(@linha,519,1),
dataDesativacao=SUBSTR(@linha,520,8),
chamadaCapa=SUBSTR(@linha,531,30),
edicao=SUBSTR(@linha,561,4),
tipoRecolhimento=SUBSTR(@linha,570,1),
classeSocial=SUBSTR(@linha,570,2),
periodicidade=SUBSTR(@linha,573,3),
formaFiscal=SUBSTR(@linha,576,2),
sexo=SUBSTR(@linha,578,1),
idade=SUBSTR(@linha,579,1),
lancamento=SUBSTR(@linha,580,1),
temaPrincipal=SUBSTR(@linha,581,2),
temaSecundario=SUBSTR(@linha,583,2),
categoria=SUBSTR(@linha,585,3),
contextoProdReferencia=SUBSTR(@linha,588,1),
codFornecProdReferencia=SUBSTR(@linha,589,1),
codProdReferencia=SUBSTR(@linha,596,12),
tipoDesconto=SUBSTR(@linha,608,2),
contextoEditor=SUBSTR(@linha,610,1),
codigoEditor=SUBSTR(@linha,611,7),
codContexto=SUBSTR(@linha,618,1),
codFornecPublicacao=SUBSTR(@linha,619,7),
codColecao=SUBSTR(@linha,626,3),
formaInclusao=SUBSTR(@linha,629,1),
codPublicacao=SUBSTR(@linha,630,8),
campoObscuro=SUBSTR(@linha,638,6),
nomeComercial=SUBSTR(@linha,644,45),
classificacao=SUBSTR(@linha,689,30),
segmento=SUBSTR(@linha,581,2),
fornecedorId=1;

LOAD DATA INFILE '/opt/rollout/load_files/00000002.prd' INTO TABLE CARGA_PRODIN_PRD CHARACTER SET UTF8
(@linha) SET 
codDistrib=SUBSTR(@linha,1,7),
dataGeracaoArquivo=SUBSTR(@linha,8,8),
contextoProd=SUBSTR(@linha,26,1),
codForncProd=SUBSTR(@linha,27,7),
codigoProduto=SUBSTR(@linha,34,8),
codigoEdicao=SUBSTR(@linha,42,4),
nome=SUBSTR(@linha,46,30),
codigoBarras=SUBSTR(@linha,76,18),
codigoBarrasCorporativo=SUBSTR(@linha,94,18),
peso=SUBSTR(@linha,112,5),
tipoProd=SUBSTR(@linha,117,3),
peb=SUBSTR(@linha,120,3),
largura=SUBSTR(@linha,123,5),
comprimento=SUBSTR(@linha,128,5),
espessura=SUBSTR(@linha,133,5),
situacaoTributaria=SUBSTR(@linha,138,1),
tributacaoFiscal=SUBSTR(@linha,139,1),
pacotePadrao=SUBSTR(@linha,140,8),
tipoMaterialPromocional=SUBSTR(@linha,148,3),
tipoMaterialDivulgacao=SUBSTR(@linha,151,3),
tipoMaterialTroca=SUBSTR(@linha,154,3),
valorValeDesconto=SUBSTR(@linha,157,10),
valorMaterialTroca=SUBSTR(@linha,167,10),
formaComercializacao=SUBSTR(@linha,177,3),
contemBrinde=SUBSTR(@linha,204,1),
codNBM=SUBSTR(@linha,205,10),
descBrinde=SUBSTR(@linha,217,300),
condVendeSeparado=SUBSTR(@linha,517,1),
status=SUBSTR(@linha,519,1),
dataDesativacao=SUBSTR(@linha,520,8),
chamadaCapa=SUBSTR(@linha,531,30),
edicao=SUBSTR(@linha,561,4),
tipoRecolhimento=SUBSTR(@linha,570,1),
classeSocial=SUBSTR(@linha,570,2),
periodicidade=SUBSTR(@linha,573,3),
formaFiscal=SUBSTR(@linha,576,2),
sexo=SUBSTR(@linha,578,1),
idade=SUBSTR(@linha,579,1),
lancamento=SUBSTR(@linha,580,1),
temaPrincipal=SUBSTR(@linha,581,2),
temaSecundario=SUBSTR(@linha,583,2),
categoria=SUBSTR(@linha,585,3),
contextoProdReferencia=SUBSTR(@linha,588,1),
codFornecProdReferencia=SUBSTR(@linha,589,1),
codProdReferencia=SUBSTR(@linha,596,12),
tipoDesconto=SUBSTR(@linha,608,2),
contextoEditor=SUBSTR(@linha,610,1),
codigoEditor=SUBSTR(@linha,611,7),
codContexto=SUBSTR(@linha,618,1),
codFornecPublicacao=SUBSTR(@linha,619,7),
codColecao=SUBSTR(@linha,626,3),
formaInclusao=SUBSTR(@linha,629,1),
codPublicacao=SUBSTR(@linha,630,8),
campoObscuro=SUBSTR(@linha,638,6),
nomeComercial=SUBSTR(@linha,644,45),
classificacao=SUBSTR(@linha,689,30),
segmento=SUBSTR(@linha,581,2),
fornecedorId=2;

