select sum(1) as count,cnpj from carga_prodin_edi
group by cnpj
having count > 1


select sum(1) as count,inscricaoEstadual from db_09795816.carga_prodin_edi
group by cnpj
having count > 1
-- --------------------------------------------------------------------------------  
-- CPF  
-- --------------------------------------------------------------------------------  
DELIMITER //
  
CREATE FUNCTION `validarCpf`(CPF CHAR(11)) RETURNS double  
BEGIN  
    DECLARE INDICE INT;  
    DECLARE SOMA INT;  
    DECLARE DIG1 INT;  
    DECLARE DIG2 INT;  
    DECLARE CPF_TEMP VARCHAR(11);  
    DECLARE DIGITOS_IGUAIS CHAR(1);  
    DECLARE RESULTADO CHAR(1);  
  
    SET RESULTADO = FALSE;  
  
    /*  
    Verificando se os dígitos são iguais  
    A Principio CPF com todos o números iguais são Inválidos  
    apesar de validar o Calculo do digito verificado  
    EX: O CPF 00000000000 é inválido, mas pelo calculo  
    Validaria  
    */  
  
    SET CPF_TEMP = SUBSTRING(CPF,1,1);  
  
    SET INDICE = 1;  
    SET DIGITOS_IGUAIS = 'S';  
  
    WHILE (INDICE <= 11) DO  
        IF (SUBSTRING(CPF,INDICE,1) <> CPF_TEMP) Then  
            SET DIGITOS_IGUAIS = 'N';  
        END IF;  
        SET INDICE = INDICE + 1;  
    END WHILE;  
  
    /*Caso os dígitos não sejam todos iguais Começo o calculo do dígitos*/  
    IF (DIGITOS_IGUAIS = 'N') THEN  
        /*Cálculo do 1º dígito*/  
        SET SOMA = 0;  
        SET INDICE = 1;  
        WHILE (INDICE <= 9) DO           SET Soma = Soma + CAST(SUBSTRING(CPF,INDICE,1) AS UNSIGNED) * (11 - INDICE);            SET INDICE = INDICE + 1;        END WHILE;      SET DIG1 = 11 - (SOMA % 11);        IF (DIG1 > 9) THEN  
            SET DIG1 = 0;  
        END IF;  
  
        -- Cálculo do 2º dígito }  
        SET SOMA = 0;  
        SET INDICE = 1;  
        WHILE (INDICE <= 10) DO          SET Soma = Soma + CAST(SUBSTRING(CPF,INDICE,1) AS UNSIGNED) * (12 - INDICE);            SET INDICE = INDICE + 1;        END WHILE;      SET DIG2 = 11 - (SOMA % 11);        IF DIG2 > 9 THEN  
            SET DIG2 = 0;  
        END IF;  
  
        -- Validando  
        IF (DIG1 = SUBSTRING(CPF,LENGTH(CPF)-1,1)) AND (DIG2 = SUBSTRING(CPF,LENGTH(CPF),1)) THEN  
            SET RESULTADO = TRUE;  
        ELSE  
            SET RESULTADO = FALSE;  
        END IF;  
  
    END IF;  
    RETURN RESULTADO;  
END//

DELIMITER ;

-- --------------------------------------------------------------------------------  
-- Inscricao Estadual 
-- --------------------------------------------------------------------------------  

DELIMITER // 

FUNCTION validarInscricaoEstadual(V_ESTADO,V_INSCRICAO)
************************************************************************
* A PRESENTE FUNÇÃO TEM COMO OBJETIVO VERIFICAR E VALIDAR A INSCRIÇÃO 
* ESTADUAL SEGUINDO O LAY-OUT APRESENTADO NO SITE DO SINTEGRA 
* CADA ESTADO POSSUI O SEU ALGORITMO E SUA FORMA DE VALIDAR A IE. 
* QUEM QUISER MELHORAR O CÓDIGO OU OTIMIZÁ-LO FIQUE A VONTADE 
* O INTUITO DESTE ESPAÇO É PARA ISTO: UM AJUDAR O OUTRO. 
* CONTRIBUIÇÃO: FLÁVIO DANTAS EMAIL: FLSD@CLICK21.COM.BR 
************************************************************************

* A VARIÁVEL DE ENTRADA V_INSCRICAO É DO TIPO CARACTER
* CASO O ESTABELECIMENTO SEJA ISENTO DE IE O 
* CAMPO DEVERÁ ESTAR PREENCHIDO COM ‘ISENTO’

* PRIMEIRO DEVEMOS RETIRAR ALGUNS CARACTERES QUE NÃO SERÃO NECESSÁRIOS
* NA VERIFICAÇÃO DA IE

V_INSCRICAO = ALLTRIM(V_INSCRICAO)
V_INSCRICAO = STRTRAN(V_INSCRICAO,'.','')
V_INSCRICAO = STRTRAN(V_INSCRICAO,'-','')
V_INSCRICAO = STRTRAN(V_INSCRICAO,'/','')
V_INSCRICAO = STRTRAN(V_INSCRICAO,',','')
V_INSCRICAO = STRTRAN(V_INSCRICAO,'ME','')
V_INSCRICAO = STRTRAN(V_INSCRICAO,' ','')
V_INSCRICAO = ALLTRIM(V_INSCRICAO)

IF V_INSCRICAO = 'ISENTO'
RETURN .T.
ENDIF

* VERIFICAMOS SE HÁ ALGUN CARACTER INVÁLIDO NA STRING
TAMANHO=LEN(V_INSCRICAO)
FOR T=1 TO TAMANHO
DIGITO=SUBSTR(ALLTRIM(V_INSCRICAO),T,1)
IF !(DIGITO $ '0123456789P')
RETURN .F.
ENDIF
NEXT

* A PARTIR DAQUI FAREMOS A VERIFICAÇÃO DA IE POR ESTADO
DO CASE
CASE V_ESTADO = 'AC'
TAMANHO=LEN(ALLTRIM(V_INSCRICAO))
IE_AC=LEFT(ALLTRIM(V_INSCRICAO),TAMANHO-2)
DV_AC=RIGHT(ALLTRIM(V_INSCRICAO),2)
COEF_AC='43298765432'
IF LEN(IE_AC) <> LEN(COEF_AC)
RETURN .F.
ENDIF
SOMA=0
DV1=''
FOR L=1 TO LEN(IE_AC)
A=VAL(SUBSTR(IE_AC,L,1))
B=VAL(SUBSTR(COEF_AC,L,1))
SOMA=SOMA + (A*B)
NEXT
V_RESTO=MOD(SOMA,11)
IF V_RESTO <= 1
DV1='0'
ELSE
N=INT(11-V_RESTO)
DV1=PADL(N,1,'0')
ENDIF

IE_AC=LEFT(ALLTRIM(V_INSCRICAO),TAMANHO-1)
COEF_AC='543298765432'
SOMA=0
DV2=''

FOR L=1 TO LEN(IE_AC)
A=VAL(SUBSTR(IE_AC,L,1))
B=VAL(SUBSTR(COEF_AC,L,1))
SOMA=SOMA + (A*B)
NEXT
V_RESTO=MOD(SOMA,11)
IF V_RESTO <= 1
DV2='0'
ELSE
N=INT(11-V_RESTO)
DV2=PADL(N,1,'0')
ENDIF
DV_OK=DV1+DV2
IF DV_AC = DV_OK
RETURN .T.
ELSE
RETURN .F.
ENDIF

CASE V_ESTADO = 'AL'
TAMANHO=LEN(ALLTRIM(V_INSCRICAO))
IE_AL=LEFT(ALLTRIM(V_INSCRICAO),TAMANHO-1)
DV_AL=RIGHT(ALLTRIM(V_INSCRICAO),1)
COEF_AL='23456789'
IF LEN(IE_AL) <> LEN(COEF_AL)
RETURN .F.
ENDIF
NOVO_IE=''
FOR L=LEN(IE_AL) TO 1 STEP -1
NOVO_IE=NOVO_IE+SUBSTR(IE_AL,L,1)
NEXT
SOMA=0
DV=''
FOR L=1 TO LEN(NOVO_IE)
A=VAL(SUBSTR(NOVO_IE,L,1))
B=VAL(SUBSTR(COEF_AL,L,1))
SOMA=SOMA + (A*B)
NEXT
V_PRODUTO = SOMA * 10
INTEIRO = INT(V_PRODUTO/11)

V_RESTO = INT(V_PRODUTO - (INTEIRO*11))

IF V_RESTO = 10
DV='0'
ELSE
DV=PADL(V_RESTO,1,'0')
ENDIF

IF DV_AL = DV
RETURN .T.
ELSE
RETURN .F.
ENDIF

CASE V_ESTADO = 'AP'
TAMANHO=LEN(ALLTRIM(V_INSCRICAO))
IE_AP=LEFT(ALLTRIM(V_INSCRICAO),TAMANHO-1)
DV_AP=RIGHT(ALLTRIM(V_INSCRICAO),1)
COEF_AP='98765432'

IF LEN(IE_AP) <> LEN(COEF_AP)
RETURN .F.
ENDIF

*De 03000001 a 03017000=> p= 5 e d= 0
*De 03017001 a 03019022=> p= 9 e d= 1
*De 03019023 em diante===>p= 0 e d= 0

P=0
D=0

DO CASE
CASE VAL(IE_AP) >= 03000001 AND VAL(IE_AP) <= 03017000
P=5
D=0
CASE VAL(IE_AP) >= 03017001 AND VAL(IE_AP) <= 03019022
P=9
D=1
CASE VAL(IE_AP) >= 03019023
P=0
D=0
ENDCASE
SOMA=0
DV=''
FOR L=1 TO LEN(IE_AP)
A=VAL(SUBSTR(IE_AP,L,1))
B=VAL(SUBSTR(COEF_AP,L,1))
SOMA=SOMA + (A*B)
NEXT
V_RESTO=MOD(P+SOMA,11)
N=INT(11-V_RESTO)

DO CASE
CASE N <10
DV=PADL(N,1,'0')
CASE N = 10
DV='0'
OTHERWISE
DV=PADL(D,1,'0')
ENDCASE
IF DV_AP = DV
RETURN .T.
ELSE
RETURN .F.
ENDIF

CASE V_ESTADO = 'AM'
COEF_AM='98765432'
TAMANHO=LEN(ALLTRIM(V_INSCRICAO))
IE_AM=LEFT(ALLTRIM(V_INSCRICAO),TAMANHO-1)
DV_AM=RIGHT(ALLTRIM(V_INSCRICAO),1)

IF LEN(IE_AM) <> LEN(COEF_AM)
RETURN .F.
ENDIF

SOMA=0
DV=''

FOR L=1 TO LEN(IE_AM)
A=VAL(SUBSTR(IE_AM,L,1))
B=VAL(SUBSTR(COEF_AM,L,1))
SOMA=SOMA + (A*B)
NEXT

V_RESTO=MOD(SOMA,11)

IF V_RESTO <= 1
DV='0'
ELSE
N=INT(11-V_RESTO)
DV=PADL(N,1,'0')
ENDIF
IF DV_AM = DV
RETURN .T.
ELSE
RETURN .F.
ENDIF

CASE V_ESTADO = 'BA'
TIPO=LEN(ALLTRIM(V_INSCRICAO))
DO CASE
CASE TIPO = 8
IF LEFT(ALLTRIM(V_INSCRICAO),1) $ '0,1,2,3,4,5,8'
TAMANHO=LEN(ALLTRIM(V_INSCRICAO))
IE_BA=LEFT(ALLTRIM(V_INSCRICAO),TAMANHO-2)
DV_BA=RIGHT(ALLTRIM(V_INSCRICAO),2)
COEF_BA='765432'
IF LEN(IE_BA) <> LEN(COEF_BA)
RETURN .F.
ENDIF
SOMA=0
DV2=''
FOR L=1 TO LEN(IE_BA)
A=VAL(SUBSTR(IE_BA,L,1))
B=VAL(SUBSTR(COEF_BA,L,1))
SOMA=SOMA + (A*B)
NEXT
V_RESTO=MOD(SOMA,10)
IF V_RESTO <= 1
DV2='0'
ELSE
N=INT(10-V_RESTO)
DV2=PADL(N,1,'0')
ENDIF

IE_BA=IE_BA+RIGHT(ALLTRIM(V_INSCRICAO),1)
COEF_BA='8765432'
SOMA=0
DV1=''
FOR L=1 TO LEN(IE_BA)
A=VAL(SUBSTR(IE_BA,L,1))
B=VAL(SUBSTR(COEF_BA,L,1))
SOMA=SOMA + (A*B)
NEXT
V_RESTO=MOD(SOMA,10)
IF V_RESTO <= 1
DV1='0'
ELSE
N=INT(10-V_RESTO)
DV1=PADL(N,1,'0')
ENDIF
DV_OK=DV1+DV2
IF DV_BA = DV_OK
RETURN .T.
ELSE
RETURN .F.
ENDIF
ELSE
TAMANHO=LEN(ALLTRIM(V_INSCRICAO))
IE_BA=LEFT(ALLTRIM(V_INSCRICAO),TAMANHO-2)
DV_BA=RIGHT(ALLTRIM(V_INSCRICAO),2)
COEF_BA='765432'
IF LEN(IE_BA) <> LEN(COEF_BA)
RETURN .F.
ENDIF
SOMA=0
DV2=''
FOR L=1 TO LEN(IE_BA)
A=VAL(SUBSTR(IE_BA,L,1))
B=VAL(SUBSTR(COEF_BA,L,1))
SOMA=SOMA + (A*B)
NEXT
V_RESTO=MOD(SOMA,11)
IF V_RESTO <= 1
DV2='0'
ELSE
N=INT(10-V_RESTO)
DV2=PADL(N,1,'0')
ENDIF

IE_BA=LEFT(ALLTRIM(V_INSCRICAO),TAMANHO-1)
COEF_BA='8765432'
SOMA=0
DV1=''
FOR L=1 TO LEN(IE_BA)
A=VAL(SUBSTR(IE_BA,L,1))
B=VAL(SUBSTR(COEF_BA,L,1))
SOMA=SOMA + (A*B)
NEXT
V_RESTO=MOD(SOMA,11)
IF V_RESTO <= 1
DV1='0'
ELSE
N=INT(11-V_RESTO)
DV1=PADL(N,1,'0')
ENDIF
DV_OK=DV1+DV2
IF DV_BA = DV_OK
RETURN .T.
ELSE
RETURN .F.
ENDIF
ENDIF
CASE TIPO = 9
IF LEFT(ALLTRIM(V_INSCRICAO),1) $ '0,1,2,3,4,5,8'
TAMANHO=LEN(ALLTRIM(V_INSCRICAO))
IE_BA=LEFT(ALLTRIM(V_INSCRICAO),TAMANHO-2)
DV_BA=RIGHT(ALLTRIM(V_INSCRICAO),2)
COEF_BA='8765432'
IF LEN(IE_BA) <> LEN(COEF_BA)
RETURN .F.
ENDIF
SOMA=0
DV2=''
FOR L=1 TO LEN(IE_BA)
A=VAL(SUBSTR(IE_BA,L,1))
B=VAL(SUBSTR(COEF_BA,L,1))
SOMA=SOMA + (A*B)
NEXT
V_RESTO=MOD(SOMA,10)
IF V_RESTO <= 1
DV2='0'
ELSE
N=INT(10-V_RESTO)
DV2=PADL(N,1,'0')
ENDIF

IE_BA=LEFT(ALLTRIM(V_INSCRICAO),TAMANHO-1)
COEF_BA='98765432'
SOMA=0
DV2=''
FOR L=1 TO LEN(IE_BA)
A=VAL(SUBSTR(IE_BA,L,1))
B=VAL(SUBSTR(COEF_BA,L,1))
SOMA=SOMA + (A*B)
NEXT
V_RESTO=MOD(SOMA,10)
IF V_RESTO <= 1
DV2='0'
ELSE
N=INT(11-V_RESTO)
DV2=PADL(N,1,'0')
ENDIF
DV_OK=DV1+DV2
IF DV_BA = DV_OK
RETURN .T.
ELSE
RETURN .F.
ENDIF
ELSE
TAMANHO=LEN(ALLTRIM(V_INSCRICAO))
IE_BA=LEFT(ALLTRIM(V_INSCRICAO),TAMANHO-2)
DV_BA=RIGHT(ALLTRIM(V_INSCRICAO),2)
COEF_BA='8765432'
IF LEN(IE_BA) <> LEN(COEF_BA)
RETURN .F.
ENDIF
SOMA=0
DV2=''
FOR L=1 TO LEN(IE_BA)
A=VAL(SUBSTR(IE_BA,L,1))
B=VAL(SUBSTR(COEF_BA,L,1))
SOMA=SOMA + (A*B)
NEXT
V_RESTO=MOD(SOMA,11)
IF V_RESTO <= 1
DV2='0'
ELSE
N=INT(10-V_RESTO)
DV2=PADL(N,1,'0')
ENDIF

IE_BA=LEFT(ALLTRIM(V_INSCRICAO),TAMANHO-1)
COEF_BA='98765432'
SOMA=0
DV2=''
FOR L=1 TO LEN(IE_BA)
A=VAL(SUBSTR(IE_BA,L,1))
B=VAL(SUBSTR(COEF_BA,L,1))
SOMA=SOMA + (A*B)
NEXT

V_RESTO=MOD(SOMA,11)

IF V_RESTO <= 1
DV2='0'
ELSE
N=INT(11-V_RESTO)
DV2=PADL(N,1,'0')
ENDIF

DV_OK=DV1+DV2

IF DV_BA = DV_OK
RETURN .T.
ELSE
RETURN .F.
ENDIF
ENDIF
ENDCASE

CASE V_ESTADO = 'CE'
COEF_CE='98765432'
TAMANHO=LEN(ALLTRIM(V_INSCRICAO))
IE_CE=LEFT(ALLTRIM(V_INSCRICAO),TAMANHO-1)
DV_CE=RIGHT(ALLTRIM(V_INSCRICAO),1)
IF LEN(IE_CE) <> LEN(COEF_CE)
RETURN .F.
ENDIF
SOMA=0
DV=''
FOR L=1 TO LEN(IE_CE)
A=VAL(SUBSTR(IE_CE,L,1))
B=VAL(SUBSTR(COEF_CE,L,1))
SOMA=SOMA + (A*B)
NEXT
V_RESTO=MOD(SOMA,11)
IF V_RESTO <= 1
DV='0'
ELSE
N=INT(11-V_RESTO)
DV=PADL(N,1,'0')
ENDIF
IF DV_CE = DV
RETURN .T.
ELSE
RETURN .F.
ENDIF

CASE V_ESTADO = 'DF'
TAMANHO=LEN(ALLTRIM(V_INSCRICAO))
IE_DF=LEFT(ALLTRIM(V_INSCRICAO),TAMANHO-2)
DV_DF=RIGHT(ALLTRIM(V_INSCRICAO),2)
COEF_DF='43298765432'
IF LEN(IE_DF) <> LEN(COEF_DF)
RETURN .F.
ENDIF
SOMA=0
DV1=''

FOR L=1 TO LEN(IE_DF)
A=VAL(SUBSTR(IE_DF,L,1))
B=VAL(SUBSTR(COEF_DF,L,1))
SOMA=SOMA + (A*B)
NEXT

V_RESTO=MOD(SOMA,11)

IF V_RESTO <= 1
DV1='0'
ELSE
N=INT(11-V_RESTO)
DV1=PADL(N,1,'0')
ENDIF

IE_DF=LEFT(ALLTRIM(V_INSCRICAO),TAMANHO-1)
COEF_DF='543298765432'
SOMA=0
DV2=''

FOR L=1 TO LEN(IE_DF)
A=VAL(SUBSTR(IE_DF,L,1))
B=VAL(SUBSTR(COEF_DF,L,1))
SOMA=SOMA + (A*B)
NEXT
V_RESTO=MOD(SOMA,11)
IF V_RESTO <= 1
DV2='0'
ELSE
N=INT(11-V_RESTO)
DV2=PADL(N,1,'0')
ENDIF
DV_OK=DV1+DV2
IF DV_DF= DV_OK
RETURN .T.
ELSE
RETURN .F.
ENDIF

CASE V_ESTADO = 'ES'
COEF_ES='98765432'
TAMANHO=LEN(ALLTRIM(V_INSCRICAO))
IE_ES=LEFT(ALLTRIM(V_INSCRICAO),TAMANHO-1)
DV_ES=RIGHT(ALLTRIM(V_INSCRICAO),1)
IF LEN(IE_ES) <> LEN(COEF_ES)
RETURN .F.
ENDIF
SOMA=0
DV=''
FOR L=1 TO LEN(IE_ES)
A=VAL(SUBSTR(IE_ES,L,1))
B=VAL(SUBSTR(COEF_ES,L,1))
SOMA=SOMA + (A*B)
NEXT
V_RESTO=MOD(SOMA,11)
IF V_RESTO <= 1
DV='0'
ELSE
N=INT(11-V_RESTO)
DV=PADL(N,1,'0')
ENDIF
IF DV_ES = DV
RETURN .T.
ELSE
RETURN .F.
ENDIF

CASE V_ESTADO = 'GO'
COEF_GO='98765432'
TAMANHO=LEN(ALLTRIM(V_INSCRICAO))
IE_GO=LEFT(ALLTRIM(V_INSCRICAO),TAMANHO-1)
DV_GO=RIGHT(ALLTRIM(V_INSCRICAO),1)
IF LEN(IE_GO) <> LEN(COEF_GO)
RETURN .F.
ENDIF
SOMA=0
DV=''

FOR L=1 TO LEN(IE_GO)
A=VAL(SUBSTR(IE_GO,L,1))
B=VAL(SUBSTR(COEF_GO,L,1))
SOMA=SOMA + (A*B)
NEXT
V_RESTO=MOD(SOMA,11)

DO CASE
CASE V_RESTO = 0
DV='0'
CASE V_RESTO = 1 AND VAL(ALLTRIM(V_INSCRICAO)) >= 10103105 ;
AND VAL(ALLTRIM(V_INSCRICAO)) <= 10119997
DV='1'
CASE V_RESTO = 1 AND (VAL(ALLTRIM(V_INSCRICAO)) < 10103105 ;
OR VAL(ALLTRIM(V_INSCRICAO)) > 10119997)
DV='1'
OTHERWISE
N=INT(11-V_RESTO)
DV=PADL(N,1,'0')
ENDCASE

IF DV_GO = DV
RETURN .T.
ELSE
RETURN .F.
ENDIF

CASE V_ESTADO = 'MA'
COEF_MA='98765432'
TAMANHO=LEN(ALLTRIM(V_INSCRICAO))
IE_MA=LEFT(ALLTRIM(V_INSCRICAO),TAMANHO-1)
DV_MA=RIGHT(ALLTRIM(V_INSCRICAO),1)
IF LEN(IE_MA) <> LEN(COEF_MA)
RETURN .F.
ENDIF
SOMA=0
DV=''
FOR L=1 TO LEN(IE_MA)
A=VAL(SUBSTR(IE_MA,L,1))
B=VAL(SUBSTR(COEF_MA,L,1))
SOMA=SOMA + (A*B)
NEXT
V_RESTO=MOD(SOMA,11)
IF V_RESTO <= 1
DV='0'
ELSE
N=INT(11-V_RESTO)
DV=PADL(N,1,'0')
ENDIF
IF DV_MA = DV
RETURN .T.
ELSE
RETURN .F.
ENDIF

CASE V_ESTADO = 'MT'
COEF_MT='3298765432'
TAMANHO=LEN(ALLTRIM(V_INSCRICAO))
IE_MT=LEFT(ALLTRIM(V_INSCRICAO),TAMANHO-1)
DV_MT=RIGHT(ALLTRIM(V_INSCRICAO),1)
IF LEN(IE_MT) <> LEN(COEF_MT)
RETURN .F.
ENDIF
SOMA=0
DV=''

FOR L=1 TO LEN(IE_MT)
A=VAL(SUBSTR(IE_MT,L,1))
B=VAL(SUBSTR(COEF_MT,L,1))
SOMA=SOMA + (A*B)
NEXT
V_RESTO=MOD(SOMA,11)

IF V_RESTO <= 1
DV='0'
ELSE
N=INT(11-V_RESTO)
DV=PADL(N,1,'0')
ENDIF
IF DV_MT = DV
RETURN .T.
ELSE
RETURN .F.
ENDIF

CASE V_ESTADO = 'MS'
COEF_MS='98765432'
TAMANHO=LEN(ALLTRIM(V_INSCRICAO))
IE_MS=LEFT(ALLTRIM(V_INSCRICAO),TAMANHO-1)
DV_MS=RIGHT(ALLTRIM(V_INSCRICAO),1)
IF LEN(IE_MS) <> LEN(COEF_MS)
RETURN .F.
ENDIF
SOMA=0
DV=''
FOR L=1 TO LEN(IE_MS)
A=VAL(SUBSTR(IE_MS,L,1))
B=VAL(SUBSTR(COEF_MS,L,1))
SOMA=SOMA + (A*B)
NEXT
V_RESTO=MOD(SOMA,11)

DV=''
DO CASE
CASE V_RESTO = 0
DV='0'
CASE V_RESTO > 0
T=INT(11-V_RESTO)
IF T > 9
DV='0'
ENDIF
IF T < 10
DV=PADL(T,1,'0')
ENDIF
ENDCASE
IF DV_MS = DV
RETURN .T.
ELSE
RETURN .F.
ENDIF

CASE V_ESTADO = 'MG'
TAMANHO=LEN(ALLTRIM(V_INSCRICAO))

IE_MG=SUBSTR(ALLTRIM(V_INSCRICAO),1,3)+'0'+;
SUBSTR(ALLTRIM(V_INSCRICAO),4,TAMANHO-2)

IE_DV=RIGHT(ALLTRIM(V_INSCRICAO),2)

SOMA=0
DV=''
FOR L=1 TO TAMANHO-2
A=VAL(SUBSTR(IE_MG,L,1))
IF MOD(L,2)=0
B=2
ELSE
B=1
ENDIF
PRODUTO = (A*B)
IF PRODUTO < 10
SOMA=SOMA + PRODUTO
ELSE
MAIOR=PADL(INT(PRODUTO),2,'0')
S1=VAL(LEFT(MAIOR,1))
S2=VAL(RIGHT(MAIOR,1))
SOMA=SOMA+S1+S2
ENDIF
NEXT
SOMA=INT(SOMA)
DEZENA1=PADL(SOMA,2,'0')
IF RIGHT(DEZENA1,1) = '0'
DEZENA2=VAL(DEZENA1)+10
ELSE
DEZENA2=(VAL(LEFT(DEZENA1,1))+1)*10
ENDIF
DV1=PADL(INT(DEZENA2 - SOMA),1,'0')

SOMA=0
IE_MG=LEFT(ALLTRIM(V_INSCRICAO),TAMANHO-1)
COEF_MG='32@#98765432'

FOR L=1 TO LEN(IE_MG)
PRODUTO=0
A=VAL(SUBSTR(IE_MG,L,1))
B=SUBSTR(COEF_MG,L,1)
IF B <> '@' AND B <> '#'
C=VAL(B)
PRODUTO = (A*C)
SOMA=SOMA + PRODUTO
ELSE
IF B = '@'
PRODUTO = A * 11
SOMA=SOMA + PRODUTO
ELSE
PRODUTO = A * 10
SOMA=SOMA + PRODUTO
ENDIF
ENDIF
NEXT
V_RESTO=MOD(SOMA,11)
IF V_RESTO <= 1
DV2='0'
ELSE
N=INT(11-V_RESTO)
DV2=PADL(N,1,'0')
ENDIF
DV=DV1+DV2
IF IE_DV = DV
RETURN .T.
ELSE
RETURN .F.
ENDIF

CASE V_ESTADO = 'PA'
COEF_PA='98765432'
TAMANHO=LEN(ALLTRIM(V_INSCRICAO))
IE_PA=LEFT(ALLTRIM(V_INSCRICAO),TAMANHO-1)
DV_PA=RIGHT(ALLTRIM(V_INSCRICAO),1)
IF LEN(IE_PA) <> LEN(COEF_PA)
RETURN .F.
ENDIF
SOMA=0
DV=''
FOR L=1 TO LEN(IE_PA)
A=VAL(SUBSTR(IE_PA,L,1))
B=VAL(SUBSTR(COEF_PA,L,1))
SOMA=SOMA + (A*B)
NEXT
V_RESTO=MOD(SOMA,11)
IF V_RESTO <= 1
DV='0'
ELSE
N=INT(11-V_RESTO)
DV=PADL(N,1,'0')
ENDIF
IF DV_PA = DV
RETURN .T.
ELSE
RETURN .F.
ENDIF

CASE V_ESTADO = 'PB'
COEF_PB='98765432'
TAMANHO=LEN(ALLTRIM(V_INSCRICAO))
IE_PB=LEFT(ALLTRIM(V_INSCRICAO),TAMANHO-1)
DV_PB=RIGHT(ALLTRIM(V_INSCRICAO),1)
IF LEN(IE_PB) <> LEN(COEF_PB)
RETURN .F.
ENDIF
SOMA=0
DV=''
FOR L=1 TO LEN(IE_PB)
A=VAL(SUBSTR(IE_PB,L,1))
B=VAL(SUBSTR(COEF_PB,L,1))
SOMA=SOMA + (A*B)
NEXT
V_RESTO=MOD(SOMA,11)
IF V_RESTO <= 1
DV='0'
ELSE
N=INT(11-V_RESTO)
DV=PADL(N,1,'0')
ENDIF
IF DV_PB = DV
RETURN .T.
ELSE
RETURN .F.
ENDIF

CASE V_ESTADO = 'PR'
TAMANHO=LEN(ALLTRIM(V_INSCRICAO))
IE_PR=LEFT(ALLTRIM(V_INSCRICAO),TAMANHO-2)
INICIO_COEF=VAL(LEFT(IE_PR,1))
DV_PR=RIGHT(ALLTRIM(V_INSCRICAO),2)
CONTA_COEF=2
COEF_PR=''
FOR L=LEN(IE_PR) TO 1 STEP -1
IF CONTA_COEF <= 7
COEF_PR=COEF_PR+PADL(CONTA_COEF,1,'0')
ELSE
CONTA_COEF=2
COEF_PR=COEF_PR+PADL(CONTA_COEF,1,'0')
ENDIF
CONTA_COEF=CONTA_COEF+1
NEXT
NOVO_IE_PR=''

FOR L=LEN(IE_PR) TO 1 STEP -1
NOVO_IE_PR=NOVO_IE_PR+SUBSTR(IE_PR,L,1)
NEXT

IF LEN(IE_PR) <> LEN(COEF_PR)
RETURN .F.
ENDIF

SOMA=0
DV=''
FOR L=1 TO LEN(IE_PR)
A=VAL(SUBSTR(NOVO_IE_PR,L,1))
B=VAL(SUBSTR(COEF_PR,L,1))
PRODUTO = A * B
SOMA=SOMA + PRODUTO
NEXT

V_RESTO=MOD(SOMA,11)
N=INT(11-V_RESTO)
DV1=PADL(N,1,'0')

IE_PR=IE_PR+LEFT(DV_PR,1)
NOVO_IE_PR=''
FOR L=LEN(IE_PR) TO 1 STEP -1
NOVO_IE_PR=NOVO_IE_PR+SUBSTR(IE_PR,L,1)
NEXT

CONTA_COEF=2
COEF_PR=''

FOR L=LEN(IE_PR) TO 1 STEP -1
IF CONTA_COEF <= 7
COEF_PR=COEF_PR+PADL(CONTA_COEF,1,'0')
ELSE
CONTA_COEF=2
COEF_PR=COEF_PR+PADL(CONTA_COEF,1,'0')
ENDIF
CONTA_COEF=CONTA_COEF+1
NEXT

IF LEN(IE_PR) <> LEN(COEF_PR)
RETURN .F.
ENDIF

SOMA=0
DV=''

FOR L=1 TO LEN(IE_PR)
A=VAL(SUBSTR(NOVO_IE_PR,L,1))
B=VAL(SUBSTR(COEF_PR,L,1))
PRODUTO = A * B
SOMA=SOMA + PRODUTO
NEXT

V_RESTO=MOD(SOMA,11)

IF V_RESTO <= 1
DV2='0'
ELSE
N=INT(11-V_RESTO)
DV2=PADL(N,1,'0')
ENDIF
DV=DV1+DV2

IF DV_PR = DV
RETURN .T.
ELSE
RETURN .F.
ENDIF

CASE V_ESTADO = 'PE'
TAMANHO=LEN(ALLTRIM(V_INSCRICAO))
NUMERO_IE=ALLTRIM(V_INSCRICAO)
DIGITOS=RIGHT(ALLTRIM(V_INSCRICAO),2)
TAMANHO=LEN(ALLTRIM(NUMERO_IE))
INICIO_CHK=8
SOMA_CHK=0

FOR L=1 TO 7
VALOR_AUX=VAL(SUBSTR(NUMERO_IE,L,1)) * INICIO_CHK
SOMA_CHK=SOMA_CHK + VALOR_AUX
INICIO_CHK=INICIO_CHK-1
NEXT
M_V_RESTO1 = MOD(SOMA_CHK,11)
IF M_V_RESTO1 = 1 OR M_V_RESTO1 = 0
DV1='0'
ELSE
DV1=INT(11- M_V_RESTO1)
ENDIF

INICIO_CHK=9
SOMA_CHK=0
FOR L=1 TO 8
VALOR_AUX=VAL(SUBSTR(NUMERO_IE,L,1)) * INICIO_CHK
SOMA_CHK=SOMA_CHK + VALOR_AUX
INICIO_CHK=INICIO_CHK-1
NEXT

M_V_RESTO2 = MOD(SOMA_CHK,11)
IF M_V_RESTO2 = 1 OR M_V_RESTO2 = 0
DV2='0'
ELSE
DV2=INT(11- M_V_RESTO2)
ENDIF
DV=PADL(DV1,1,'0')+PADL(DV2,1,'0')

IF DV = DIGITOS
RETURN .T.
ELSE
RETURN .F.
ENDIF

CASE V_ESTADO = 'PI'
COEF_PI='98765432'
TAMANHO=LEN(ALLTRIM(V_INSCRICAO))
IE_PI=LEFT(ALLTRIM(V_INSCRICAO),TAMANHO-1)
DV_PI=RIGHT(ALLTRIM(V_INSCRICAO),1)
IF LEN(IE_PI) <> LEN(COEF_PI)
RETURN .F.
ENDIF
SOMA=0
DV=''
FOR L=1 TO LEN(IE_PI)
A=VAL(SUBSTR(IE_PI,L,1))
B=VAL(SUBSTR(COEF_PI,L,1))
SOMA=SOMA + (A*B)
NEXT
V_RESTO=MOD(SOMA,11)
IF V_RESTO <= 1
DV='0'
ELSE
N=INT(11-V_RESTO)
DV=PADL(N,1,'0')
ENDIF
IF DV_PI = DV
RETURN .T.
ELSE
RETURN .F.
ENDIF

CASE V_ESTADO = 'RN'
TAMANHO=LEN(ALLTRIM(V_INSCRICAO))
IE_RN=LEFT(ALLTRIM(V_INSCRICAO),TAMANHO-1)
DV_RN=RIGHT(ALLTRIM(V_INSCRICAO),1)

IF LEN(IE_RN) = 8
COEF_RN='98765432'
A=LEN(IE_RN)
B=LEN(COEF_RN)
IF A <> B
RETURN .F.
ENDIF
SOMA=0
DV=''

FOR L=1 TO LEN(IE_RN)
A=VAL(SUBSTR(IE_RN,L,1))
B=VAL(SUBSTR(COEF_RN,L,1))
SOMA=SOMA + (A*B)
NEXT
V_RESTO=MOD(SOMA,11)

IF V_RESTO <= 1
DV='0'
ELSE
N=INT(11-V_RESTO)
DV=PADL(N,1,'0')
ENDIF

IF DV_RN = DV
RETURN .T.
ELSE
RETURN .F.
ENDIF
ELSE
COEF_RN='198765432'
IF LEN(IE_RN) <> LEN(COEF_RN)
RETURN .F.
ENDIF
SOMA=0
DV=''

FOR L=1 TO LEN(IE_RN)
A=VAL(SUBSTR(IE_RN,L,1))
B=VAL(SUBSTR(COEF_RN,L,1))
IF B = 1
B = 10
ENDIF
SOMA=SOMA + (A*B)
NEXT

V_RESTO=MOD(SOMA,11)
IF V_RESTO = 10
DV='0'
ELSE
IF V_RESTO <= 1
DV='0'
ELSE
N=INT(11-V_RESTO)
DV=PADL(N,1,'0')
ENDIF
ENDIF
IF DV_RN = DV
RETURN .T.
ELSE
RETURN .F.
ENDIF
ENDIF

CASE V_ESTADO = 'RS'
COEF_RS='298765432'
TAMANHO=LEN(ALLTRIM(V_INSCRICAO))
IE_RS=LEFT(ALLTRIM(V_INSCRICAO),TAMANHO-1)
DV_RS=RIGHT(ALLTRIM(V_INSCRICAO),1)
IF LEN(IE_RS) <> LEN(COEF_RS)
RETURN .F.
ENDIF
SOMA=0
DV=''
FOR L=1 TO LEN(IE_RS)
A=VAL(SUBSTR(IE_RS,L,1))
B=VAL(SUBSTR(COEF_RS,L,1))
SOMA=SOMA + (A*B)
NEXT
V_RESTO=MOD(SOMA,11)

IF V_RESTO <= 1
DV='0'
ELSE
N=INT(11-V_RESTO)
DV=PADL(N,1,'0')
ENDIF

IF DV_RS = DV
RETURN .T.
ELSE
RETURN .F.
ENDIF

CASE V_ESTADO = 'RO'
COEF_RO='6543298765432'
TAMANHO=LEN(ALLTRIM(V_INSCRICAO))
IE_RO=LEFT(ALLTRIM(V_INSCRICAO),TAMANHO-1)
DV_RO=RIGHT(ALLTRIM(V_INSCRICAO),1)
IF LEN(IE_RO) <> LEN(COEF_RO)
RETURN .F.
ENDIF
SOMA=0
DV=''
FOR L=1 TO LEN(IE_RO)
A=VAL(SUBSTR(IE_RO,L,1))
B=VAL(SUBSTR(COEF_RO,L,1))
SOMA=SOMA + (A*B)
NEXT
V_RESTO=MOD(SOMA,11)
IF V_RESTO <= 1
DV='0'
ELSE
N=INT(11-V_RESTO)
DV=PADL(N,1,'0')
ENDIF

IF DV_RO = DV
RETURN .T.
ELSE
RETURN .F.
ENDIF

CASE V_ESTADO = 'RR'
TAMANHO=LEN(ALLTRIM(V_INSCRICAO))
IE_RR=LEFT(ALLTRIM(V_INSCRICAO),TAMANHO-1)
DV_RR=RIGHT(ALLTRIM(V_INSCRICAO),1)
COEF_RR=''

FOR L=1 TO LEN(IE_RR)
IF L < 9
COEF_RR=COEF_RR+PADL(L,1,'0')
ELSE
COEF_RR=COEF_RR+PADL(L-8,1,'0')
ENDIF
NEXT

IF LEN(IE_RR) <> LEN(COEF_RR)
RETURN .F.
ENDIF
SOMA=0
DV=''

FOR L=1 TO LEN(IE_RR)
A=VAL(SUBSTR(IE_RR,L,1))
B=VAL(SUBSTR(COEF_RR,L,1))
SOMA=SOMA + (A*B)
NEXT

V_RESTO=MOD(SOMA,9)
DV=PADL(V_RESTO,1,'0')

IF DV_RR = DV
RETURN .T.
ELSE
RETURN .F.
ENDIF

CASE V_ESTADO = 'RJ'
COEF_RJ='2765432'
TAMANHO=LEN(ALLTRIM(V_INSCRICAO))
IE_RJ=LEFT(ALLTRIM(V_INSCRICAO),TAMANHO-1)
DV_RJ=RIGHT(ALLTRIM(V_INSCRICAO),1)
IF LEN(IE_RJ) <> LEN(COEF_RJ)
RETURN .F.
ENDIF
SOMA=0
DV=''

FOR L=1 TO LEN(IE_RJ)
A=VAL(SUBSTR(IE_RJ,L,1))
B=VAL(SUBSTR(COEF_RJ,L,1))
SOMA=SOMA + (A*B)
NEXT

V_RESTO=MOD(SOMA,11)
IF V_RESTO <= 1
DV='0'
ELSE
N=INT(11-V_RESTO)
DV=PADL(N,1,'0')
ENDIF

IF DV_RJ = DV
RETURN .T.
ELSE
RETURN .F.
ENDIF

CASE V_ESTADO = 'SC'
COEF_SC='98765432'
TAMANHO=LEN(ALLTRIM(V_INSCRICAO))
IE_SC=LEFT(ALLTRIM(V_INSCRICAO),TAMANHO-1)
DV_SC=RIGHT(ALLTRIM(V_INSCRICAO),1)
IF LEN(IE_SC) <> LEN(COEF_SC)
RETURN .F.
ENDIF
SOMA=0
DV=''

FOR L=1 TO LEN(IE_SC)
A=VAL(SUBSTR(IE_SC,L,1))
B=VAL(SUBSTR(COEF_SC,L,1))
SOMA=SOMA + (A*B)
NEXT

V_RESTO=MOD(SOMA,11)

IF V_RESTO <= 1
DV='0'
ELSE
N=INT(11-V_RESTO)
DV=PADL(N,1,'0')
ENDIF

IF DV_SC = DV
RETURN .T.
ELSE
RETURN .F.
ENDIF

CASE V_ESTADO = 'SP'
IF LEFT(ALLTRIM(V_INSCRICAO),1) <> 'P'
COEF_SP='1345678*'
TAMANHO=LEN(ALLTRIM(V_INSCRICAO))
IE_SP=LEFT(ALLTRIM(V_INSCRICAO),TAMANHO)

SOMA=0
DV=''

FOR L=1 TO 8
A=VAL(SUBSTR(IE_SP,L,1))
B=SUBSTR(COEF_SP,L,1)
IF B = '*'
B = 10
ELSE
B=VAL(B)
ENDIF
PRODUTO=A*B
SOMA=SOMA + PRODUTO
NEXT

V_RESTO=MOD(SOMA,11)

IF V_RESTO = 10
DV1='0'
ELSE
DV1=INT(V_RESTO)
DV1=PADL(DV1,1,'0')
DV1=RIGHT(DV1,1)
ENDIF

COEF_SP='32*98765432'
SOMA=0
DV=''
FOR L=1 TO 11
A=VAL(SUBSTR(IE_SP,L,1))
B=SUBSTR(COEF_SP,L,1)
IF B = '*'
B = 10
ELSE
B=VAL(B)
ENDIF
PRODUTO=A*B
SOMA=SOMA + PRODUTO
NEXT
V_RESTO=MOD(SOMA,11)
DV2=INT(V_RESTO)
DV2=PADL(DV2,1,'0')
DV2=RIGHT(DV2,1)
A=SUBSTR(ALLTRIM(V_INSCRICAO),9,1)
B=SUBSTR(ALLTRIM(V_INSCRICAO),12,1)
IF A = DV1 AND B = DV2
RETURN .T.
ELSE
RETURN .F.
ENDIF
ELSE
COEF_SP='1345678*'
TAMANHO=LEN(SUBSTR(ALLTRIM(V_INSCRICAO),2,8))
IE_SC=SUBSTR(ALLTRIM(V_INSCRICAO),2,8)

SOMA=0
DV=''

FOR L=1 TO LEN(IE_SC)
A=VAL(SUBSTR(IE_SC,L,1))
B=VAL(SUBSTR(COEF_SC,L,1))
SOMA=SOMA + (A*B)
NEXT

V_RESTO=MOD(SOMA,11)

DV=INT(V_RESTO)
DV=PADL(DV,1,'0')
DV=RIGHT(DV,1)

IF VAL(SUBSTR(ALLTRIM(V_INSCRICAO),10,1)) = DV
RETURN .T.
ELSE
RETURN .F.
ENDIF
ENDIF

CASE V_ESTADO = 'SE'
COEF_SE='98765432'
TAMANHO=LEN(ALLTRIM(V_INSCRICAO))
IE_SE=LEFT(ALLTRIM(V_INSCRICAO),TAMANHO-1)
DV_SE=RIGHT(ALLTRIM(V_INSCRICAO),1)
IF LEN(IE_SE) <> LEN(COEF_SE)
RETURN .F.
ENDIF
SOMA=0
DV=''

FOR L=1 TO LEN(IE_SE)
A=VAL(SUBSTR(IE_SE,L,1))
B=VAL(SUBSTR(COEF_SE,L,1))
SOMA=SOMA + (A*B)
NEXT
V_RESTO=MOD(SOMA,11)
IF V_RESTO <= 1
DV='0'
ELSE
N=INT(11-V_RESTO)
DV=PADL(N,1,'0')
ENDIF
IF DV_SE = DV
RETURN .T.
ELSE
RETURN .F.
ENDIF

CASE V_ESTADO = 'TO'
TAMANHO=LEN(ALLTRIM(V_INSCRICAO))
IE_TO=LEFT(ALLTRIM(V_INSCRICAO),TAMANHO-1)
DV_TO=RIGHT(ALLTRIM(V_INSCRICAO),1)
VALIDADE=SUBSTR(IE_TO,3,2)
IF VALIDADE <> '01' AND VALIDADE <> '02' AND VALIDADE <> '03'
RETURN .F.
ENDIF
IE_TO=SUBSTR(IE_TO,1,2)+SUBSTR(IE_TO,5,6)

COEF_TO='98765432'
IF LEN(IE_TO) <> LEN(COEF_TO)
RETURN .F.
ENDIF
SOMA=0
DV=''
FOR L=1 TO LEN(IE_TO)
A=VAL(SUBSTR(IE_TO,L,1))
B=VAL(SUBSTR(COEF_TO,L,1))
PRODUTO=(A*B)
SOMA=SOMA + PRODUTO
NEXT
V_RESTO=MOD(SOMA,11)
IF V_RESTO <= 1
DV='0'
ELSE
N=INT(11-V_RESTO)
DV=PADL(N,1,'0')
ENDIF
IF DV_TO = DV
RETURN .T.
ELSE
RETURN .F.
ENDIF
ENDCASE
RETURN .F.
