INSERT INTO USUARIO VALUES(1, "jfonseca", "Júnior Fonseca", MD5("1234"));

INSERT INTO PERMISSAO VALUES(1, "Cadastro de banco", "Financeiro.Cadastro.Banco");
INSERT INTO PERMISSAO VALUES(2, "Administrador", "Admin");
INSERT INTO PERMISSAO VALUES(3, "Cadastro de Fiador", "Financeiro.Cadastro.FIADOR");

INSERT INTO GRUPO_PERMISSOES VALUES(1, "Financeiro"); 

INSERT INTO GRUPO_PERMISSOES_PERMISSAO VALUES(1, 1);

INSERT INTO USUARIO_GRUPO_PERMISSOES VALUES(1, 1);
