DROP VIEW IF EXISTS VIEW_NOTA_FISCAL;

CREATE OR REPLACE VIEW VIEW_NOTA_FISCAL AS

(
SELECT
'ENTRADA' AS NOTAS_DE,
CASE WHEN (PESSOA_FORNECEDOR.ID IS NOT NULL) THEN PESSOA_FORNECEDOR.ID ELSE PESSOA_COTA.ID END AS PESSOA_ID,
NOTA_FISCAL_ENTRADA.TIPO AS TIPO,
NOTA_FISCAL_ENTRADA.CHAVE_ACESSO AS CHAVE_ACESSO,
NOTA_FISCAL_ENTRADA.DATA_EMISSAO AS DATA_EMISSAO,
NOTA_FISCAL_ENTRADA.DATA_EXPEDICAO AS DATA_EXPEDICAO,
NOTA_FISCAL_ENTRADA.EMITIDA AS EMITIDA,
NOTA_FISCAL_ENTRADA.NUMERO AS NUMERO,
NOTA_FISCAL_ENTRADA.SERIE AS SERIE,
NOTA_FISCAL_ENTRADA.STATUS_EMISSAO AS STATUS_EMISSAO,
NOTA_FISCAL_ENTRADA.VALOR_BRUTO AS VALOR_BRUTO,
NOTA_FISCAL_ENTRADA.VALOR_DESCONTO AS VALOR_DESCONTO,
NOTA_FISCAL_ENTRADA.VALOR_LIQUIDO AS VALOR_LIQUIDO,
NOTA_FISCAL_ENTRADA.TIPO_EMISSAO_NFE AS TIPO_EMISSAO_NFE,
NOTA_FISCAL_ENTRADA.MOVIMENTO_INTEGRACAO AS MOVIMENTO_INTEGRACAO,
NOTA_FISCAL_ENTRADA.STATUS_EMISSAO_NFE AS STATUS_EMISSAO_NFE,

NOTA_FISCAL_ENTRADA.ORIGEM AS ORIGEM,
NOTA_FISCAL_ENTRADA.STATUS_NOTA_FISCAL,

NOTA_FISCAL_ENTRADA.CFOP_ID AS CFOP_ID,
NOTA_FISCAL_ENTRADA.PJ_ID AS PJ_ID,
NOTA_FISCAL_ENTRADA.TIPO_NF_ID AS TIPO_NF_ID,

NOTA_FISCAL_ENTRADA.USUARIO_ID AS USUARIO_ID,
NOTA_FISCAL_ENTRADA.COTA_ID AS COTA_ID,
NOTA_FISCAL_ENTRADA.FORNECEDOR_ID AS FORNECEDOR_ID

FROM NOTA_FISCAL_ENTRADA

LEFT JOIN FORNECEDOR ON (
    NOTA_FISCAL_ENTRADA.FORNECEDOR_ID IS NULL OR 
    NOTA_FISCAL_ENTRADA.FORNECEDOR_ID = FORNECEDOR.ID
) 

LEFT JOIN PESSOA AS PESSOA_FORNECEDOR ON (
    FORNECEDOR.JURIDICA_ID IS NULL OR
    FORNECEDOR.JURIDICA_ID = PESSOA_FORNECEDOR.ID
) 

LEFT JOIN COTA ON (
    NOTA_FISCAL_ENTRADA.COTA_ID IS NULL OR 
    NOTA_FISCAL_ENTRADA.COTA_ID = COTA.ID
) 

LEFT JOIN PESSOA AS PESSOA_COTA ON (
    COTA.PESSOA_ID IS NULL OR
    COTA.PESSOA_ID = PESSOA_COTA.ID
)

) UNION ( 

SELECT  
'SAIDA' AS NOTAS_DE,
PESSOA_FORNECEDOR.ID AS PESSOA_ID,
NOTA_FISCAL_SAIDA.TIPO AS TIPO,
NOTA_FISCAL_SAIDA.CHAVE_ACESSO AS CHAVE_ACESSO,
NOTA_FISCAL_SAIDA.DATA_EMISSAO AS DATA_EMISSAO,
NOTA_FISCAL_SAIDA.DATA_EXPEDICAO AS DATA_EXPEDICAO,
NOTA_FISCAL_SAIDA.EMITIDA AS EMITIDA,
NOTA_FISCAL_SAIDA.NUMERO AS NUMERO,
NOTA_FISCAL_SAIDA.SERIE AS SERIE,
NOTA_FISCAL_SAIDA.STATUS_EMISSAO AS STATUS_EMISSAO,
NOTA_FISCAL_SAIDA.VALOR_BRUTO AS VALOR_BRUTO,
NOTA_FISCAL_SAIDA.VALOR_DESCONTO AS VALOR_DESCONTO,
NOTA_FISCAL_SAIDA.VALOR_LIQUIDO AS VALOR_LIQUIDO,
NOTA_FISCAL_SAIDA.TIPO_EMISSAO_NFE AS TIPO_EMISSAO_NFE,
NOTA_FISCAL_SAIDA.MOVIMENTO_INTEGRACAO AS MOVIMENTO_INTEGRACAO,
NOTA_FISCAL_SAIDA.STATUS_EMISSAO_NFE AS STATUS_EMISSAO_NFE,


NULL AS ORIGEM,
NULL AS STATUS_NOTA_FISCAL,

NOTA_FISCAL_SAIDA.CFOP_ID AS CFOP_ID,
NOTA_FISCAL_SAIDA.PJ_ID AS PJ_ID,
NOTA_FISCAL_SAIDA.TIPO_NF_ID AS TIPO_NF_ID,

NULL AS USUARIO_ID,
NULL AS COTA_ID,

NOTA_FISCAL_SAIDA.FORNECEDOR_ID AS FORNECEDOR_ID

FROM NOTA_FISCAL_SAIDA 

INNER JOIN FORNECEDOR ON (
    NOTA_FISCAL_SAIDA.FORNECEDOR_ID = FORNECEDOR.ID
) 

INNER JOIN PESSOA AS PESSOA_FORNECEDOR ON (
    FORNECEDOR.JURIDICA_ID = PESSOA_FORNECEDOR.ID
) 

)
 








