package br.com.abril.nds.enums;

import java.util.HashSet;
import java.util.Set;

/**
 * @author francisco.garcia
 * @version 1.0
 * @created 14-fev-2012 11:35:33
 */
public enum TipoParametroSistema {

	PATH_ARQUIVOS_DISTRIBUICAO_COTA,
	
	PATH_IMAGENS_CAPA,

	PATH_IMAGENS_PDV,
	
	PATH_TERMO_ADESAO,
	
	PATH_PROCURACAO,
		
	INBOUND_DIR_NOTA_VAREJO,
	/**
	 * Número de dias permitido para lançamento de uma diferença de estoque do
	 * tipo FALTA DE.
	 */
	NUMERO_DIAS_PERMITIDO_LANCAMENTO_FALTA_DE,

	/**
	 * Número de dias permitido para lançamento de uma diferença de estoque do
	 * tipo FALTA EM.
	 */
	NUMERO_DIAS_PERMITIDO_LANCAMENTO_FALTA_EM,

	/**
	 * Número de dias permitido para lançamento de uma diferença de estoque do
	 * tipo SOBRA DE.
	 */
	NUMERO_DIAS_PERMITIDO_LANCAMENTO_SOBRA_DE,

	/**
	 * Número de dias permitido para lançamento de uma diferença de estoque do
	 * tipo SOBRA EM.
	 */
	NUMERO_DIAS_PERMITIDO_LANCAMENTO_SOBRA_EM,
	
	/**
	 * Número de dias permitido para lançamento de uma Alteracao de Reparte
	 */
	NUMERO_DIAS_PERMITIDO_ALTERACAO_REPARTE_LANCAMENTO,

	/**
	 * SMTP de autenticação da conta de e-mail do sistema
	 */
	EMAIL_PROTOCOLO,

	/**
	 * Senha de autenticação da conta de e-mail do sistema
	 */
	EMAIL_SENHA,

	/**
	 * Número da Porta de autenticação da conta de e-mail do sistema
	 */
	EMAIL_PORTA,

	/**
	 * Nome do host de autenticação da conta de e-mail do sistema
	 */
	EMAIL_HOST,

	/**
	 * Usúario de de autenticação da conta de e-mail do sistema
	 */
	EMAIL_USUARIO,
	
	/**
	 * Remetente para envio de e-mail do sistema
	 */
	EMAIL_REMETENTE,

	/**
	 * Autentica o envio de e-mail do sistema
	 */
	EMAIL_AUTENTICAR,
	
	/**
	 * Representa a quantidade de meses que sera efetuado o expurgo do sistema
	 */
	FREQUENCIA_EXPURGO,

	// TODO remover esse parametro após a alteração do "TODO" que se incontra na
	// classe br.com.abril.nds.integracao.engine.CouchDBImportDataRouter
	CODIGO_DISTRIBUIDOR_DINAP, LOGOTIPO_DISTRIBUIDOR,

	VERSAO_SISTEMA,

	PATH_IMPORTACAO_CONTRATO, PATH_INTERFACE_CE_EXPORTACAO, PATH_INTERFACE_PICKING_EXPORTACAO, PATH_INTERFACE_PRODIN_IMPORTACAO, PATH_INTERFACE_PRODIN_EXPORTACAO, PATH_INTERFACE_MDC_IMPORTACAO, PATH_INTERFACE_MDC_EXPORTACAO, PATH_INTERFACE_MDC_BACKUP, PATH_INTERFACE_BANCAS_EXPORTACAO, PATH_INTERFACE_GFS_IMPORTACAO, PATH_INTERFACE_GFS_EXPORTACAO, PATH_INTERFACE_NFE_IMPORTACAO, PATH_INTERFACE_NFE_EXPORTACAO, PATH_GERACAO_ARQUIVO_COBRANCA,

	DATA_OPERACAO_CORRENTE, // formato: dd/MM/yyyy

	//
	NDSI_EMS0106_ARCHIVE, NDSI_EMS0106_INBOUND, NDSI_EMS0106_IN_FILEMASK, NDSI_EMS0107_ARCHIVE, NDSI_EMS0107_INBOUND, NDSI_EMS0107_OUTBOUND, NDSI_EMS0107_IN_FILEMASK, NDSI_EMS0107_OUT_FILEMASK, NDSI_EMS0108_ARCHIVE, NDSI_EMS0108_INBOUND, NDSI_EMS0108_IN_FILEMASK, NDSI_EMS0109_ARCHIVE, NDSI_EMS0109_INBOUND, NDSI_EMS0110_ARCHIVE, NDSI_EMS0110_INBOUND, NDSI_EMS0110_OUTBOUND, NDSI_EMS0110_IN_FILEMASK, NDSI_EMS0112_ARCHIVE, NDSI_EMS0112_INBOUND, NDSI_EMS0112_IN_FILEMASK, NDSI_EMS0114_ARCHIVE, NDSI_EMS0114_INBOUND, NDSI_EMS0114_OUTBOUND, NDSI_EMS0114_IN_FILEMASK, NDSI_EMS0116_ARCHIVE, NDSI_EMS0116_INBOUND, NDSI_EMS0116_OUTBOUND, NDSI_EMS0116_IN_FILEMASK, NDSI_EMS0117_ARCHIVE, NDSI_EMS0117_INBOUND, NDSI_EMS0117_OUTBOUND, NDSI_EMS0117_IN_FILEMASK, NDSI_EMS0118_ARCHIVE, NDSI_EMS0118_INBOUND, NDSI_EMS0118_IN_FILEMASK, NDSI_EMS0119_ARCHIVE, NDSI_EMS0119_INBOUND, NDSI_EMS0119_IN_FILEMASK, NDSI_EMS0120_OUTBOUND, NDSI_EMS0121_OUTBOUND, NDSI_EMS0122_OUTBOUND, NDSI_EMS0123_OUTBOUND, NDSI_EMS0124_OUTBOUND, NDSI_EMS0129_ARCHIVE, NDSI_EMS0129_OUTBOUND, NDSI_EMS0129_OUT_FILEMASK, NDSI_EMS0131_OUTBOUND, NDSI_EMS0133_OUTBOUND, OUTBOUND_FOLDER,
	
	CNPJ_PJ_IMPORTACAO_NRE,

	INBOUND_DIR, INTERNAL_DIR, IMAGE_DIR, CORREIOS_DIR,
	
	NFE_INFORMACOES_VERSAO_EMISSOR
	, NFE_INFORMACOES_AMBIENTE
	, NFE_INFORMACOES_TIPO_EMISSOR
	, NFE_INFORMACOES_FORMATO_IMPRESSAO
	, NFE_INFORMACOES_MODELO_DOCUMENTO
	, NFE_LIMITAR_QTDE_ITENS
	, NFE_PATH_CERTIFICADO,
	
	FTF_INDEX_FILENAME,
	
	PATH_INTERFACE_NFE_EXPORTACAO_FTF,
	PATH_INTERFACE_NFE_IMPORTACAO_FTF,
	
	FTF_CODIGO_ESTABELECIMENTO_EMISSOR,
    
	FTF_CNPJ_ESTABELECIMENTO_EMISSOR,
	
	FTF_CODIGO_LOCAL,
    
	FTF_CODIGO_CENTRO_EMISSOR,
	
	PATH_TRANSFERENCIA_ARQUIVO,
	
	PATH_INTERFACE_NFE_EXPORTACAO_TXT,
	;

	
	
	public static final Set<TipoParametroSistema> TIPOS_INTERFACE = new HashSet<TipoParametroSistema>();
	static {
		TIPOS_INTERFACE.add(PATH_INTERFACE_CE_EXPORTACAO);
		TIPOS_INTERFACE.add(PATH_INTERFACE_PRODIN_IMPORTACAO);
		TIPOS_INTERFACE.add(PATH_INTERFACE_PRODIN_EXPORTACAO);
		TIPOS_INTERFACE.add(PATH_INTERFACE_MDC_IMPORTACAO);
		TIPOS_INTERFACE.add(PATH_INTERFACE_MDC_EXPORTACAO);
		TIPOS_INTERFACE.add(PATH_INTERFACE_MDC_BACKUP);
		TIPOS_INTERFACE.add(PATH_INTERFACE_BANCAS_EXPORTACAO);
		TIPOS_INTERFACE.add(PATH_INTERFACE_GFS_IMPORTACAO);
		TIPOS_INTERFACE.add(PATH_INTERFACE_GFS_EXPORTACAO);
		TIPOS_INTERFACE.add(PATH_INTERFACE_NFE_IMPORTACAO);
		TIPOS_INTERFACE.add(PATH_INTERFACE_NFE_EXPORTACAO);
		TIPOS_INTERFACE.add(PATH_INTERFACE_PICKING_EXPORTACAO);
		TIPOS_INTERFACE.add(PATH_INTERFACE_NFE_EXPORTACAO_FTF);
		TIPOS_INTERFACE.add(PATH_INTERFACE_NFE_IMPORTACAO_FTF);
		TIPOS_INTERFACE.add(PATH_INTERFACE_NFE_EXPORTACAO_TXT);
	}
}